### ISSUE TITLE
Remove Steven Feldman from Committee

### ISSUE THREAD

**Issue by archaeogeek** [osgeouk/committee#1]
Tasks to do:

- [x] Change official address for organisation

- [x] Change address for tax

- [x] Remove from oseouk gmail

- [x] Remove from lastpass

- [x] Update website

**Comment by archaeogeek** [comment]
@mtravis I need to do something similar to this issue for my own handover- but I'm just checking whether we did the unticked bits or not?

**Comment by mtravis** [comment]
We changed the bank address but not the bank branch I believe.

Also need to check with Steven if he removed his details from lastpass?

**Comment by stevenfeldman** [comment]
I can remove all the last pass password settings but I think I am the admin for the sharing settings which may cause some issues

Let me know if you want me to try that
______
Steven

Unusual maps in strange places -  mappery.org <http://mappery.org/>

Subscribe to my weekly “Maps in the Wild <http://eepurl.com/dKStT-/>” newsletter

**Comment by archaeogeek** [comment]
Hold fire on lastpass for now I think.

**Comment by nickbearman** [comment]
@mtravis did you successfully take over lastpass from Steven? If so I think we can close this now.

**Comment by mtravis** [comment]
I did and will close now.

**Comment by stevenfeldman** [comment]
I’ll delete the entries in my personal last pass
______
Steven

Unusual maps in strange places -  mappery.org <http://mappery.org/>

Subscribe to my weekly “Maps in the Wild <http://eepurl.com/dKStT-/>” newsletter
